package nft

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Ploos-AS/Ploos-Application-Gateway/internal/config"
)

// Render returns an nftables ruleset for review/dry-run.
// M1 never applies the generated ruleset.
func Render(c *config.Config) (string, error) {
	if err := c.Validate(); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# generated by PAG; M1 dry-run only\n")
	b.WriteString("table inet pag {\n")
	b.WriteString("  chain forward {\n")
	b.WriteString("    type filter hook forward priority 0; policy drop;\n")

	names := make([]string, 0, len(c.Zones))
	for name := range c.Zones {
		names = append(names, name)
	}
	sort.Strings(names)

	// M1 deliberately emits no generic accept rules. A proxied flow must
	// terminate locally at its gateway; direct forwarding remains denied.
	for _, name := range names {
		z := c.Zones[name]
		for _, iface := range z.Interfaces {
			if err := validateIdentifier(iface); err != nil {
				return "", fmt.Errorf("zone %q: %w", name, err)
			}
			fmt.Fprintf(&b, "    # zone %s interface %s\n", name, iface)
		}
	}

	for _, r := range c.Policy.Rules {
		if r.Action == "proxy" {
			fmt.Fprintf(&b, "    # %s: %s -> %s protocol %s via %s; direct forwarding stays blocked\n",
				r.Name, r.From, r.To, r.Protocol, r.Gateway)
		}
	}

	b.WriteString("  }\n")
	b.WriteString("}\n")
	return b.String(), nil
}

func validateIdentifier(s string) error {
	if s == "" {
		return fmt.Errorf("empty interface name")
	}
	for _, r := range s {
		if !(r == '-' || r == '_' || r == '.' || r == ':' ||
			r >= '0' && r <= '9' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z') {
			return fmt.Errorf("unsafe interface name %q", s)
		}
	}
	return nil
}
